spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/base?currentSchema=public
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    #open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true

server:
  error:
    whitelabel:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
#      springframework:
#        security: TRACE
      hibernate:
#        SQL: DEBUG
        orm:
          jdbc:
            bind: TRACE
        stat: DEBUG
        SQL_SLOW: INFO
        cache: DEBUG